# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee6829aa55d39c5433a79744ff2d7cb720feed684132efd4d5972b32099df8eb4d0b3d19849e87be47d7c18823e9284cb9e60a623ba173c32e1d779db9bb0f9

test:
  secret_key_base: 1f2de13aff83cbaabf6fa10b9a4d6a175be9c37b3f58e74c607e379779586e31024edf9241ae1f0ebc3f854b6bfef42818876b29c42390100aa52ecb94c7fd6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
